# ideally you wont put these in your git repo, just as a sample
apiVersion: v1
stringData:
  password: "yourpassword"
  username: "yourusername"
kind: Secret
metadata:
  annotations:
    tekton.dev/git-0: https://github.com/gituser
  name: gitcredential
  namespace: yournamespace
type: kubernetes.io/basic-auth
