FROM clearlinux/node:12.13.0

ENV TINI_VERSION v0.18.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

RUN mkdir /web
WORKDIR /web
COPY package.json /web

RUN npm install
COPY *.js /web

CMD ["node","--prof","/web/index.js"]